# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75b971e1ddc8c22432350e2797cc44f39634cfe97bd3615bba042191fb87f953282bab5f3c6aaffcc7ff28e831be43be51028d23db2ba81601268ac9c0a2f1f7

test:
  secret_key_base: 29d8acf8babf28d11b7857091e5a1755037bc823f419c23d86ccd8baf2d6245526d32c5f0e079dbe2832451f38069f197b6d5614c89c1dd79e50e78f7722d5ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
